apiVersion: v1
kind: Service
metadata:
  name: clusterip-db-name
  namespace: my-db
  labels:
    app: clusterip-db-label
    owner: babak
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: sql-in-deployment