apiVersion: v1
kind: Service
metadata:
  name: nodeport-app-name
  namespace: my-app
  labels:
    app: nodeport-app-label
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: app-in-deployment