apiVersion: v1
kind: Service
metadata:
  name: lb-app-name
  namespace: lab3
  labels:
    name: lb-app-label
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 8080
    protocol: TCP
  selector:
    app: app-in-deployment