apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-hp-name
  namespace: lab3
  labels:
    app: db-hp-label
    owner: babak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-hp-dep
  template:
    metadata:
      labels:
       app: db-hp-dep
    spec:
      volumes:
       - name: db-vol
         persistentVolumeClaim:
           claimName: db-pvc-t8-name
      containers:
      - name: mysql
        image: 328460808357.dkr.ecr.us-east-1.amazonaws.com/a1-db:v2.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "babak"
        ports:
        - name: db-dep-ptname
          containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: db-vol
          mountPath: /data/db4g2
       
