apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-static-name
  labels:
    app: db-pv-static-label
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
 # persistentVolumeReclaimPolicy: Retain
  storageClassName: localstorage
  hostPath:
    path: /data/dbpvt8